spring.application.name=erick
# URL kết nối R2DBC cho H2
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

# Để xem console của H2 (Dùng để debug dữ liệu)
# Lưu ý: H2 Console vẫn dùng JDBC nên cần cấu hình thêm
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs




external.portcontrol.base-url=${PORTCONTROL_URL:http://localhost:80/api/portcontrol}
external.portcontrol.api-key=${PORTCONTROL_KEY:my-default-key}